### ISSUE TITLE
Automate the documentation process

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox.org#14]
The documentation currently needs a push on master to build the documentation. However, we currently need to manually build the ".md" from the shimming-toolbox repo.

- helpDocMd (Matlab) is required to convert ".m" into ".md"

**Comment by jcohenadad** [comment]
@po09i any update on this?

**Comment by po09i** [comment]
Yes, currently working on setting up azure-pipelines and a generate-doc script to fix this issue

**Comment by kousu** [comment]
I've left some comments on the docs script: https://github.com/shimming-toolbox/shimming-toolbox.org/commit/3fc74ca09d904a71787548d03967fe5c30d0f4f0.

**Comment by po09i** [comment]
The doc will eventually be moved to shimming-toolbox repo instead of this repo.

**Comment by po09i** [comment]
The building of the website was completed on shimming-toolbox repo on this [PR](https://github.com/shimming-toolbox/shimming-toolbox/pull/129) This can be closed
