### ISSUE TITLE
Decide on general organization for the website

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox.org#2]
We need to decide on a general organization for the website. Here is a suggestion (feedback needed):
- Introduction
  - if people are seeking to also implement shimming hardware, they can check out the shim amplifier design included elsewhere on the website. --> LINK TO "HARDWARE"
- Installation
- Getting started
- Support
- Contributing
  - General
  - API documentation
- Other ressources
  - Hardware
    - Description of hardware with amplifiers
    - Assembly
- Contributors
- License

**Comment by rtopfer** [comment]
^also, a "Contributing" section. (also, "Links of interest" and/or "References"...) 

The idea is that most (or all) of the documentation (.md files) within the repo master branch are included as HTML pages on the static website (e.g. GitHub Pages), right?

**Comment by jcohenadad** [comment]
> ^also, a "Contributing" section. (also, "Links of interest" and/or "References"...)

thanks-- i've updated 

> The idea is that most (or all) of the documentation (.md files) within the repo master branch are included as HTML pages on the static website (e.g. GitHub Pages), right?

yup!

**Comment by jaystock** [comment]
Julien, for the main tree on the website, I might suggest adding a link to a list of the primary people and institutions that contributed, along with their contact info if people need support.  

In the Introduction section, we could mention that if people are seeking to also implement shimming hardware, they can check out the shim amplifier design included elsewhere on the website.  And we could mention that software links exist to connect the shim GUI to the hardware.

**Comment by jcohenadad** [comment]
> Julien, for the main tree on the website, I might suggest adding a link to a list of the primary people and institutions that contributed, along with their contact info if people need support.
> 
> In the Introduction section, we could mention that if people are seeking to also implement shimming hardware, they can check out the shim amplifier design included elsewhere on the website. And we could mention that software links exist to connect the shim GUI to the hardware.

thanks @jaystock! i've edited the bullet list at the beginning to reflect your suggestions

**Comment by evaalonsoortiz** [comment]
What kind of info would go in the "Help" section?

**Comment by jcohenadad** [comment]
> What kind of info would go in the "Help" section?

who to contact, where to go (e.g. link to Forum) if people need support to use the software. We can rename as "Support".

**Comment by rtopfer** [comment]
>We can rename as "Support" if it is clearer.
I "Support" this^

**Comment by jcohenadad** [comment]
@po09i can we move forward with this?

**Comment by po09i** [comment]
Yes, [PR](https://github.com/shimming-toolbox/shimming-toolbox.org/pull/12) is now open to reviews
