### ISSUE TITLE
Info to build doc locally

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/shimming-toolbox.org#24]
Since the website gets updated on a push to master, local builds procedure should be documented.

**Comment by po09i** [comment]
First time 
- pip install mkdocs

All the time
- cd <to_shimming-toolbox.org_repo>
- mkdocs serve
- go to `http://127.0.0.1:8000` on your browser

**Comment by jcohenadad** [comment]
@po09i i'll create a wiki entry to get things started

**Comment by jcohenadad** [comment]
here: https://github.com/shimming-toolbox/shimming-toolbox.org/wiki/build-documentation

**Comment by jcohenadad** [comment]
~~~
ERROR   -  Config value: 'theme'. Error: Unrecognised theme name: 'material'. The available installed themes are: mkdocs, readthedocs 
~~~
needed: pip install material

**Comment by jcohenadad** [comment]
~~~
julien-macbook:~/code/shimming-toolbox.org $ mkdocs serve
INFO    -  Building documentation... 
ERROR   -  Config value: 'theme'. Error: Unrecognised theme name: 'material'. The available installed themes are: mkdocs, readthedocs 
~~~
@po09i any quick workaround?

**Comment by jcohenadad** [comment]
in the meantime, trying with theme `readthedocs`

**Comment by po09i** [comment]
have you tries `pip install mkdocs-material`

**Comment by jcohenadad** [comment]
that did the trick!, thanks @po09i

**Comment by po09i** [comment]
I'll update the wiki

**Comment by po09i** [comment]
Wiki was created on shimming-toolbox.org and shimming-toolbox repos. This can be closed
