### ISSUE TITLE
Decide on static HTML building tool

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox.org#3]
Jekyll, Hugo, Sphinx, Mkdocs?

I would vote for Jekyll or Mkdocs.

Jekyll:
- Popular
- No need for speed (ie we won't have thousands of pages)
- Good integration with GH pages

Mkdocs:
- @po09i already has a working build 
- https://people.xiph.org/~epirat/post/why_switch_to_mkdocs/

Resources:
- https://idratherbewriting.com/learnapidoc/pubapis_which_tool_to_choose.html
- https://www.techiediaries.com/jekyll-hugo-hexo/
- https://www.docslikecode.com/learn/

**Comment by rtopfer** [comment]
If it's just a matter of converting our Markdown documentation files to HTML is it safe to assume there wouldn't be any major differences apart from convenience?

Can we anticipate needing to add material that can't just be included in a Markdown file?

**Comment by alexfoias** [comment]
I vote Jekyll. @rtopfer Jekyll uses markdown format that is dynamically rendered to HTML using GH pages.

**Comment by rtopfer** [comment]
@alexfoias not important but i thought it was the other way around, with Jekyll rendering the text files to HTML and GH Pages simply hosting the content + providing convenient editing features?🤔

**Comment by jcohenadad** [comment]
> Can we anticipate needing to add material that can't just be included in a Markdown file?

absolutely-- figures, movies, etc.  can be physically located in the repos source (e.g. _media/) and pointed at from within the markdown page.

**Comment by jcohenadad** [comment]
If we go with GH page, the default build processor is Jekyll. If we want to change the default build processor, [here](https://help.github.com/en/github/working-with-github-pages/about-github-pages#static-site-generators) are the instructions.

**Comment by po09i** [comment]
Since I had a working build for mkdocs I implemented it using this [github action](https://github.com/mhausenblas/mkdocs-deploy-gh-pages). I'm not familiar with jekyll but I can look into it if I missed something mkdocs does not do. Currently works really well.

**Comment by jcohenadad** [comment]
@po09i can we close this?

**Comment by po09i** [comment]
Yes, we went with mkdocs.
