### ISSUE TITLE
Decide on where to host documentation

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox.org#4]
Github page vs. ReadTheDocs?

I vote for Github page.

Resource:
- https://github.com/pmd/pmd/issues/405
- https://stackshare.io/stackups/github-pages-vs-read-the-docs
- https://github.com/neuropoly/spinalcordtoolbox/issues/1656

Notes:
- We will need to have our CI build and push pages automatically

**Comment by rtopfer** [comment]
I can't speak from experience but from the little I've looked into the comparison I'm also inclined to centralize everything via GitHub.
The Pages [promo vid](https://www.youtube.com/watch?v=2MsN8gpT6jY#action=share) makes it sound easy and sufficient for our purposes.

**Comment by alexfoias** [comment]
I vote Github page.

**Comment by jcohenadad** [comment]
If going with MkDocs and GH page, [here](https://github.com/mhausenblas/mkdocs-deploy-gh-pages) is a GH action to automatize the build process. We could potentially add our custom scripts during the build (e.g. build API doc)

**Comment by jcohenadad** [comment]
seems to be a (somewhat) duplicate of https://github.com/shimming-toolbox/shimming-toolbox.org/issues/3, right @po09i ?  Looks like we went with GH actions

**Comment by po09i** [comment]
Settled on GH-pages. We can close this issue and continue working towards automating it with #14.
