### ISSUE TITLE
Select a theme

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/shimming-toolbox.org#5]
If using Jekyll:
- List of themes: http://jekyllthemes.org/
- Themes i like:
  - https://www.embeddedlog.com/jekyll-theme-rtd/

If using Mkdocs:
- List of themes: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes
- Themes i like:
  - https://gitlab.com/lramage/mkdocs-gitbook-theme
  - https://github.com/cjsheets/mkdocs-rtd-dropdown
  - https://github.com/mkdocs/mkdocs-bootstrap

**Comment by po09i** [comment]
I personally like the [material](https://github.com/squidfunk/mkdocs-material) theme for mkdocs since it has the page overview on the right.

**Comment by jcohenadad** [comment]
i have to admit that i am not a huge fan of having the TOC on the right. This is quite uncommon (probably >95% of documentations online have their TOC on the left. Also, having two TOC (one on the right, the other on the left) is a bit confusing. Maybe there is another way to rearrange this.

**Comment by evaalonsoortiz** [comment]
I like the read the docs theme for Jekyll.
For Mkdocs, I like (again) the read-the-docs theme, Windmill dark, Gitbook and Ivory.

**Comment by jcohenadad** [comment]
@po09i let's move forward with RTD theme

**Comment by po09i** [comment]
RTD was implemented. This can be closed
